apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\lahou\scoop\apps\kompose\current\kompose.exe convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: python-app
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: python-app
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\lahou\scoop\apps\kompose\current\kompose.exe convert
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: python-app
    spec:
      containers:
        - image: python-app
          name: kayezabdiel-python
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
